#!/bin/bash
#
# tarball2appimage by LinuxDicasPro
#
####################################

destdir=~/__APPIMAGE__
test -e "../_APPIMAGE" && destdir="../_APPIMAGE" # Opcional


###########################################

arch="x86_64"
prg="vscode"
link="https://github.com/microsoft/vscode/tags"

###########################################


for i in {1..35}; { printf '─'; }; printf "\n"
printf "Search latest version: "


########

version="$(grep -Eom1 "([0-9]+[.])+[0-9]+" <(grep -A5 "commit" <(links -dump "$link")))"

########


printf "\033[1;32m$version\033[m\n"
for i in {1..35}; { printf '─'; }; printf "\n"


test -z "$version" && {
    echo "update script. version not found!"
    exit 1
}

set -e

test ! -e $destdir && mkdir -p $destdir
cd $destdir


test -e "VSCode-$version-$arch.AppImage" && {
    echo "appimage found!"
    exit 0
}


test ! -e "appimagetool-x86_64.AppImage" && {
    link_tool="https://github.com/AppImage/AppImageKit/releases/download/13/appimagetool-x86_64.AppImage"
    wget -c -q --show-progress "$link_tool"
    chmod +x "appimagetool-x86_64.AppImage"
}


#########

link_prg="https://update.code.visualstudio.com/$version/linux-x64/stable"

#########


wget -c -q --show-progress -O code-stable-$version.tar.gz "$link_prg"
file_prg="code-stable-$version.tar.gz"

cwd=$PWD

rm -rf "$prg.AppDir"
mkdir -p "$prg.AppDir"
cd "$prg.AppDir"

echo -e "\nextract $file_prg ..."
printf "$file_prg\t["
tar -zxf "$cwd/$file_prg" --checkpoint=500 --checkpoint-action=exec='printf ='
echo -e "]\n"

cp VSCode-linux-x64/resources/app/out/media/code-icon.svg ./$prg.svg

echo '<?xml version="1.0" encoding="UTF-8"?>
<mime-info xmlns="http://www.freedesktop.org/standards/shared-mime-info">
	<mime-type type="application/x-code-workspace">
		<comment>VSCode Workspace</comment>
		<glob pattern="*.code-workspace"/>
	</mime-type>
</mime-info>' > VSCode-linux-x64/code-workspace.xml


####################################

appimage_name="VSCode"
comment="Code Editing"
categories="Utility;TextEditor;Development;IDE;"

####################################


echo "[Desktop Entry]
Name=$appimage_name
GenericName=$appimage_name
Comment=$comment
Exec=$prg %F
Icon=$prg
Type=Application
Terminal=false
MimeType=application/x-code-workspace;
Categories=$categories
Actions=new-empty-window;
Keywords=vscode;

[Desktop Action new-empty-window]
Name=New Empty Window
Exec=$prg --new-window %F
Icon=$prg" > "$prg.desktop"

echo "[Desktop Entry]
Name=$appimage_name - URL Handler
Comment=Code Editing. Redefined.
GenericName=$appimage_name - URL Handler
Exec=$prg --open-url %U
Icon=$prg
Type=Application
NoDisplay=true
StartupNotify=true
Categories=$categories
MimeType=x-scheme-handler/vscode;
Keywords=vscode;" > "$prg-url.desktop"

echo "#!/bin/bash

cd \$APPDIR
desktopfile=~/.local/share/applications/$prg.desktop
iconfile=~/.local/share/pixmaps/$prg.svg
deskurlfile=~/.local/share/applications/$prg-url.desktop

test ! -e \"\$desktopfile\" && cp $prg.desktop ~/.local/share/applications/
test ! -e \"\$deskurlfile\" && cp $prg-url.desktop ~/.local/share/applications/
test ! -e \"\$iconfile\" && cp $prg.svg ~/.local/share/pixmaps/

if ! grep -q \"\$APPIMAGE\" \"\$desktopfile\"; then
    cp $prg.desktop ~/.local/share/applications/
    cp $prg-url.desktop ~/.local/share/applications/
    cp $prg.svg ~/.local/share/pixmaps/
    sed -i \"s:Exec=$prg:Exec=\$APPIMAGE:\" \"\$desktopfile\"
    sed -i \"s:Icon=.*:Icon=\$iconfile:\" \"\$desktopfile\"
    /usr/bin/update-desktop-database -q || true
    test -e usr/share/icons/hicolor/icon-theme.cache && {
        test -x /usr/bin/gtk-update-icon-cache && /usr/bin/gtk-update-icon-cache ~/.local/share/pixmaps/ 2>&1 >&- || true
    }

    cp \"VSCode-linux-x64/code-workspace.xml\" ~/.local/share/mime/packages
    /usr/bin/update-mime-database ~/.local/share/mime 2>&1 >&- || true
fi

cd \$APPDIR/VSCode-linux-x64
./code \"\$@\"" > AppRun

chmod +x AppRun
cd ..

printf "\n"; for ((i=0; i<$COLUMNS; i++)); { printf '─'; }; echo -e "\n"

env ARCH=$arch ./appimagetool-x86_64.AppImage "$prg.AppDir"
mv ${appimage_name// /_}*URL*-$arch.AppImage "$appimage_name-$version-$arch.AppImage"

printf "\n"; for ((i=0; i<$COLUMNS; i++)); { printf '─'; }; echo -e "\n"

rm -rf "$prg.AppDir"
cd ..

echo "appimage saved in $destdir/$appimage_name-$version-$arch.AppImage"
exit 0
